# Generated by Django 2.2.2 on 2019-06-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190616_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
