# Generated by Django 2.2.2 on 2019-06-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.FileField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Position'),
        ),
    ]
